[package]
name = "websubmit"
version = "0.1.0"
authors = ["Malte Schwarzkopf <malte@cs.brown.edu>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
noria = { git = "https://github.com/mit-pdos/noria" }
rocket = "0.4.2"
#slog = "2.4.0"
slog = { version = "2.4.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
tokio = "0.1"
